version: '3.8'

services:
  v2ray_telegram:
    container_name: v2ray_telegram
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=${PORT}
    volumes:
      - /app/.yarn/
      - ./:/app
    command: yarn start:dev
    