version: '3.7'

networks:
  default:
    external:
      name: ${NETWORK_NAME}

services:
  minio:
    container_name: ${MINIO_CONTAINER_NAME}
    restart: always
    image: minio/minio
    ports:
      - '${MINIO_PORT}:9000'
      - '${MINIO_DASHBOARD_PORT}:9001'
    expose:
      - 9000
    volumes:
      - minio-data:/data
    environment:
      MINIO_REGION_NAME: ${MINIO_REGION_NAME}
      # MINIO_SERVER_HOST: "minio-server"
      # MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      # MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

  # minio-client:
  #   image: minio/mc:RELEASE.2023-07-21T20-44-27Z
  #   entrypoint: ['/bin/sh', '-c']
  #   depends_on:
  #     - minio
  #   command:
  #     - |
  #       sleep 5
  #       mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
  #       mc mb --ignore-existing local/${MINIO_BUCKET}
  #       mc policy set download local/${MINIO_BUCKET}

volumes:
  minio-data:
    driver: local
    # driver_opts:
    #   type: none
    #   device: ${MINIO_PERSIST_PATH}
    #   o: bind
