version: '3.7'

networks:
  default:
    external:
      name: ${NETWORK_NAME}

services:
  postgres:
    image: postgres:15.3-alpine
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: postgres -c shared_buffers=${POSTGRES_SHARED_BUFFER}
    expose:
      - 5432
    ports:
      - '5432:5432'

volumes:
  postgres-data:
    driver: local


