version: '3.8'

networks:
  default:
    external:
      name: ${NETWORK_NAME}

services:
  bot:
    image: davaeiha/freedom:1.0.3
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      PORT: ${PORT}
