name: setup foundation for docker

on:
  workflow_call:

jobs:
  foundation:
    defaults:
      run:
        working-directory: .github/scripts
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
